name: Build
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Prerequesties
      run: |
        sudo apt-get install cmake cppcheck lcov python3-pip python3-setuptools
        sudo pip3 install cpplint conan
        conan remote add pureoop-2out https://conan.cloudsmith.io/pureoop/2out
    - name: Build
      run: |
        conan install . -s compiler.libcxx='libstdc++11' --build=missing
        cmake -DCMAKE_CXX_FLAGS="--coverage" .
        make style
        make VERBOSE=1
        make test
    - name: Gather coverage info
      run: |
        lcov --directory . --capture --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info
    - uses: codecov/codecov-action@v1
      with:
        files: coverage.info
