name: Deploy
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        sudo apt install python3-setuptools
        sudo pip3 install conan
        conan remote add mdf https://api.bintray.com/conan/mdf/pureoop
        conan create . dronmdf/testing
        conan user -p ${{ secrets.BINTRAY }} -r mdf dronmdf
        conan upload "*" -r mdf --all --confirm
