name: Testing deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        sudo apt install python3-setuptools
        sudo pip3 install conan
        BUILD=`git log --first-parent --oneline v0.3..HEAD | wc -l`
        sed -i "s/version = '0.4'/version = '0.4.$BUILD'/" conanfile.py
        sed -i "s/checkout('v' + self.version)/checkout('${{ github.sha }}')/" conanfile.py
        conan remote add pureoop-2out https://conan.cloudsmith.io/pureoop/2out
        conan remote add pureoop-goost https://conan.cloudsmith.io/pureoop/goost
        conan create . dronmdf/testing --build=missing
        conan user -p ${{ secrets.CLOUDSMITH }} -r pureoop-goost andrey-valyaev
        conan upload "goost/*" -r pureoop-goost --all --confirm
